trace: fix default backtrace formatter construction
That formatter is used for ad-hoc printing of samples, eg.
in error messages.

This fixes the following error message:

Traceback (most recent call last):
  File "scripts/trace.py", line 576, in <module>
    args.func(args)
  File "scripts/trace.py", line 244, in prof_lock
    show_profile(args, get_profile)
  File "scripts/trace.py", line 208, in show_profile
    max_levels=args.max_levels)
  File "/home/tgrabiec/src/osv/scripts/osv/prof.py", line 170, in print_profile
    for sample in samples:
  File "/home/tgrabiec/src/osv/scripts/osv/prof.py", line 108, in get_duration_profile
    raise Exception('Double entry:\n%s\n%s\n' % (str(old), str(trace)))
  File "/home/tgrabiec/src/osv/scripts/osv/trace.py", line 125, in __str__
    return self.format()
  File "/home/tgrabiec/src/osv/scripts/osv/trace.py", line 122, in format
    bt_formatter(self.backtrace))
  File "/home/tgrabiec/src/osv/scripts/osv/trace.py", line 32, in __call__
    frames = list(debug.resolve_all(self.resolver, (x - 1 for x in backtrace if x)))
  File "/home/tgrabiec/src/osv/scripts/osv/debug.py", line 107, in resolve_all
    return itertools.chain.from_iterable(map(resolver, raw_addresses))
TypeError: __init__() takes exactly 1 argument (2 given)

When this should actually be printed:

Traceback (most recent call last):
  File "scripts/trace.py", line 576, in <module>
    args.func(args)
  File "scripts/trace.py", line 244, in prof_lock
    show_profile(args, get_profile)
  File "scripts/trace.py", line 208, in show_profile
    max_levels=args.max_levels)
  File "/data/tgrabiec/osv/scripts/osv/prof.py", line 170, in print_profile
    for sample in samples:
  File "/data/tgrabiec/osv/scripts/osv/prof.py", line 108, in get_duration_profile
    raise Exception('Double entry:\n%s\n%s\n' % (str(old), str(trace)))
Exception: Double entry:
0xffffc00017668010                  3 1399542568.505835772 mutex_lock_wait (...)
0xffffc00017668010                  1 1399542574.668642044 mutex_lock_wait (...)

Signed-off-by: Tomasz Grabiec <tgrabiec@cloudius-systems.com>
Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>