gdb: fix 'osv info virtio'
Looks like gdb.Value() cannot be implicitly converted to int
by range() on GDB with python3:

    for qidx in range(0, vb['_num_queues']):
  TypeError: 'gdb.Value' object cannot be interpreted as an integer
  Error occurred in Python command: 'gdb.Value' object cannot be interpreted as an integer

Signed-off-by: Tomasz Grabiec <tgrabiec@cloudius-systems.com>
Signed-off-by: Avi Kivity <avi@cloudius-systems.com>