Skip lo0 when initializing interfaces in loader.cc
Attempt to reassign IP for lo0 fails and leaves it without an address.

This breaks tomcat:

  SEVERE: StandardServer.await: create[localhost:8005]:
  java.net.BindException: Address not available

Signed-off-by: Tomasz Grabiec <tgrabiec@cloudius-systems.com>
Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>