cli: Catch errors for 'perf callstack'
Currently, looking up a non-existing tracepoint kills the guest:

sun.org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: Cannot find tracepoint (/console/perf.js#91)
	at sun.org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1786)
	at sun.org.mozilla.javascript.MemberBox.newInstance(MemberBox.java:202)
	at sun.org.mozilla.javascript.NativeJavaClass.constructSpecific(NativeJavaClass.java:284)
	at sun.org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:202)
	at sun.org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2440)
	at sun.org.mozilla.javascript.gen._console_perf_js_17._c_anonymous_7(/console/perf.js:91)
	at sun.org.mozilla.javascript.gen._console_perf_js_17.call(/console/perf.js)
	at sun.org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
	at sun.org.mozilla.javascript.gen._console_perf_js_17._c_anonymous_10(/console/perf.js:114)
	at sun.org.mozilla.javascript.gen._console_perf_js_17.call(/console/perf.js)
	at sun.org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
	at sun.org.mozilla.javascript.gen._console_perf_js_17._c_anonymous_1(/console/perf.js:8)
	at sun.org.mozilla.javascript.gen._console_perf_js_17.call(/console/perf.js)
	at sun.org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
	at sun.org.mozilla.javascript.gen.cli_js_21._c_run_sync_15(cli.js:202)
	at sun.org.mozilla.javascript.gen.cli_js_21.call(cli.js)
	at sun.org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
	at sun.org.mozilla.javascript.gen.cli_js_21._c_invoke_18(cli.js:223)
	at sun.org.mozilla.javascript.gen.cli_js_21.call(cli.js)
	at sun.org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
	at sun.org.mozilla.javascript.gen.cli_js_21._c_command_19(cli.js:237)
	at sun.org.mozilla.javascript.gen.cli_js_21.call(cli.js)
	at sun.org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
	at sun.org.mozilla.javascript.gen.cli_js_21._c_main_loop_21(cli.js:290)
	at sun.org.mozilla.javascript.gen.cli_js_21.call(cli.js)
	at sun.org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
	at sun.org.mozilla.javascript.gen.cli_js_21._c_script_0(cli.js:323)
	at sun.org.mozilla.javascript.gen.cli_js_21.call(cli.js)
	at sun.org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
	at sun.org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
	at sun.org.mozilla.javascript.gen.cli_js_21.call(cli.js)
	at sun.org.mozilla.javascript.gen.cli_js_21.exec(cli.js)
	at sun.org.mozilla.javascript.Context.evaluateReader(Context.java:1142)
	at com.cloudius.cli.main.RhinoCLI.run(Unknown Source)
	at com.cloudius.cli.util.TelnetCLI.handleConnection(Unknown Source)
	at com.cloudius.cli.util.TelnetD$1.run(Unknown Source)
Caused by: java.lang.RuntimeException: Cannot find tracepoint
	at com.cloudius.trace.Tracepoint.findByName(Native Method)
	at com.cloudius.trace.Tracepoint.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at sun.org.mozilla.javascript.MemberBox.newInstance(MemberBox.java:194)
	... 34 more

Fix that by catching errors like "perf stat" does.